# Generated by Django 6.0.4 on 2026-04-13 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('category', models.CharField(choices=[('FOOD', 'Pārtika un produkti'), ('TRANSPORT', 'Transports'), ('HOUSING', 'Mājoklis un komunālie pakalpojumi'), ('HEALTH', 'Veselība'), ('ENTERTAINMENT', 'Izklaide'), ('SALARY', 'Alga'), ('OTHER', 'Cits')], default='OTHER', max_length=20, verbose_name='Kategorija')),
                ('date', models.DateField(verbose_name='Datums')),
                ('description', models.TextField(blank=True, verbose_name='Apraksts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs')),
            ],
            options={
                'verbose_name': 'Transakcija',
                'verbose_name_plural': 'Transakcijas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
